# Generated by Django 4.2.1 on 2023-06-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insucon', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
