# Generated by Django 4.0.5 on 2023-06-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insucon', '0004_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
            ],
        ),
    ]
