# Generated by Django 4.0.5 on 2023-06-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insucon', '0008_usuario_alter_userprofile_apellido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
