# Generated by Django 4.0.5 on 2023-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insucon', '0009_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
